/* eslint-disable @typescript-eslint/no-unused-vars */
// Skills Section Logo's
import htmlLogo from '../assets/tech_logo/html.png';
import cssLogo from '../assets/tech_logo/css.png';
import sassLogo from '../assets/tech_logo/sass.png';
import javascriptLogo from '../assets/tech_logo/javascript.png';
import reactjsLogo from '../assets/tech_logo/reactjs.png';
import angularLogo from '../assets/tech_logo/angular.png';
import reduxLogo from '../assets/tech_logo/redux.png';
import nextjsLogo from '../assets/tech_logo/nextjs.png';
import tailwindcssLogo from '../assets/tech_logo/tailwindcss.png';
import gsapLogo from '../assets/tech_logo/gsap.png';
import materialuiLogo from '../assets/tech_logo/materialui.png';
import bootstrapLogo from '../assets/tech_logo/bootstrap.png';
import springbootLogo from '../assets/tech_logo/springboot.png';
import nodejsLogo from '../assets/tech_logo/nodejs.png';
import expressjsLogo from '../assets/tech_logo/express.png';
import mysqlLogo from '../assets/tech_logo/mysql.png';
import mongodbLogo from '../assets/tech_logo/mongodb.png';
import firebaseLogo from '../assets/tech_logo/firebase.png';
import cLogo from '../assets/tech_logo/c.png';
import cppLogo from '../assets/tech_logo/cpp.png';
import javaLogo from '../assets/tech_logo/java.png';
import pythonLogo from '../assets/tech_logo/python.png';
import typescriptLogo from '../assets/tech_logo/typescript.png';
import gitLogo from '../assets/tech_logo/git.png';
import githubLogo from '../assets/tech_logo/github.png';
import vscodeLogo from '../assets/tech_logo/vscode.png';
import postmanLogo from '../assets/tech_logo/postman.png';
import mcLogo from '../assets/tech_logo/mc.png';
import figmaLogo from '../assets/tech_logo/figma.png';
import netlifyLogo from '../assets/tech_logo/netlify.png';
import vercelLogo from '../assets/tech_logo/vercel.png';
import postgreLogo from '../assets/tech_logo/postgresql.png';
import csharpLogo from '../assets/tech_logo/csharp.png';
import dockerLogo from '../assets/tech_logo/docker.png';
import zustandLogo from '../assets/tech_logo/zustand.png';
import shadcnLogo from '../assets/tech_logo/shadcn.png';
import betterAuthLogo from '../assets/tech_logo/better-auth.png';
import zodLogo from '../assets/tech_logo/zod.png';
import reactHookFormLogo from '../assets/tech_logo/react-hook-form.png';
import tanstackLogo from '../assets/tech_logo/tanstack.png';
import jestLogo from '../assets/tech_logo/jest.png';
import swaggerLogo from '../assets/tech_logo/swagger.png';
import prismaLogo from '../assets/tech_logo/prisma.png';
import reactRouterDomLogo from '../assets/tech_logo/react-router-dom.png';

// Experience Section Logo's
import digitalentLogo from '../assets/company_logo/dts-logo.png';
import productzillaAcademyLogo from '../assets/company_logo/productzilla_logo.png';
import revouLogo from '../assets/company_logo/revou_logo.png';
import hariSeninLogo from '../assets/company_logo/harisenin_logo.png';

// Education Section Logo's
import bsiLogo from '../assets/education_logo/bsi_logo.png';
import nusaMandiriLogo from '../assets/education_logo/nusamandiri_logo.png';

// Project Section Logo's
import dentWisePreview from '../assets/work_logo/dentwise_preview.png';
import signalistPreview from '../assets/work_logo/signalist_preview.png';
import chillFEPreview from '../assets/work_logo/chill_preview.png';
import chillBEPreview from '../assets/work_logo/chill_preview.png';
